#ifndef _ST_UTIL_H
#define _ST_UTIL_H

#include <stddef.h>

#define USAGE_STRING \
    "\nUsage: penglai_sign <commands> [options] file...\n"\
    "Commands:\n"\
    "   sign                    Sign the enclave using the private key\n"\
    "   gendata                 Generate enclave signing material to be signed\n"\
    "   catsig                  Generate the signed enclave with the input signature file, the\n"\
    "                           public key and the enclave signing material\n"\
    "   dump                    Dump metadata information for a signed enclave file\n"\
    "Options:\n"\
    "   -image                  Specify the kernel image file to be signed\n"\
    "   -imageaddr              Specify the kernel image's load address\n"\
    "   -dtb                    Specify the device tree file\n"\
    "   -dtbaddr                Specify the device tree file's load address\n"\
    "                           These four options are required for \"sign\", \"gendata\" and \"catsig\"\n"\
    "   -key                    Specify the key file\n"\
    "                           It is a required option for \"sign\" and \"catsig\"\n"\
    "   -out                    Specify the output file\n"\
    "                           It is a required option for \"sign\", \"gendata\" and \"catsig\"\n"\
    "   -sig                    Specify the signature file for the enclave signing material\n" \
    "                           It is a required option for \"catsig\"\n"\
    "   -unsigned               Specify the enclave signing material generated by \"gendata\"\n" \
    "                           It is a required option for \"catsig\"\n" \
    "   -ccsfile                Specify the Cryper Certificate Struct file to be dumped in human readable form\n"\
    "                           It is a required option for \"dump\"\n"\
    "   -dumpfile               Specify a file to dump Cryper Certificate Struct file in human readable form\n" \
    "                           It is a required option for \"dump\", and a optional option for \"sign\" and \"catsig\"\n" \
    "Run \"penglai_sign -help\" to get this help and exit.\n"

typedef enum _command_mode_t
{
    SIGN = 0,
    GENDATA,
    CATSIG,
    DUMP
} command_mode_t;

void printHex(unsigned char *c, int n);
int get_file_size(const char *filename);
int read_file_to_buf(const char *filename, unsigned char *buffer, size_t bsize, long offset);
int write_data_to_file(const char *filename, const char *modes, unsigned char *buf, size_t bsize, long offset);
int copy_file(const char *source_path, const char *dest_path);

#endif